# Generated by Django 6.0.1 on 2026-01-23 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birth_year', models.PositiveIntegerField(blank=True, null=True)),
                ('death_year', models.PositiveIntegerField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True, help_text='Biography for programme notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this programme')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('catalogue_number', models.CharField(blank=True, help_text='e.g., BWV 1079, Op. 10', max_length=50)),
                ('instrumentation', models.CharField(blank=True, help_text='e.g., Alto, Tenor, Bass recorders', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Programme notes about this piece')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('composer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='repertoire.composer')),
            ],
            options={
                'ordering': ['composer__name', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('item_type', models.CharField(choices=[('piece', 'Piece'), ('talk', 'Talk'), ('interval', 'Interval')], default='piece', max_length=20)),
                ('title', models.CharField(blank=True, help_text="Title for talk or interval (e.g., 'Introduction', 'Interval')", max_length=200)),
                ('talk_text', models.TextField(blank=True, help_text='Text/notes for what to say during the talk')),
                ('custom_duration', models.PositiveIntegerField(blank=True, help_text='Duration in minutes (for talks/intervals)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this item')),
                ('piece', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programme_items', to='repertoire.piece')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='repertoire.programme')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
