# Generated by Django 6.0.1 on 2026-01-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmeitem',
            name='speaker',
            field=models.CharField(blank=True, help_text='Name of the person giving the talk', max_length=200),
        ),
    ]
