# Generated by Django 6.0.1 on 2026-01-23 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0002_programmeitem_speaker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(help_text="e.g., 'I. Allegro', 'II. Adagio'", max_length=200)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='repertoire.piece')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
