# Generated by Django 6.0.1 on 2026-01-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0003_movement'),
    ]

    operations = [
        migrations.AddField(
            model_name='composer',
            name='birth_year_qualifier',
            field=models.CharField(blank=True, choices=[('', '—'), ('c.', 'c.'), ('after', 'after'), ('before', 'before')], max_length=10),
        ),
        migrations.AddField(
            model_name='composer',
            name='death_year_qualifier',
            field=models.CharField(blank=True, choices=[('', '—'), ('c.', 'c.'), ('after', 'after'), ('before', 'before')], max_length=10),
        ),
    ]
