# Generated by Django 6.0.1 on 2026-01-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0004_composer_birth_year_qualifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='composer',
            name='dates_override',
            field=models.CharField(blank=True, help_text="Override computed dates, e.g. 'fl. late 14th century'", max_length=100),
        ),
        migrations.AlterField(
            model_name='composer',
            name='birth_year_qualifier',
            field=models.CharField(blank=True, choices=[('', '—'), ('c.', 'c.'), ('after', 'after'), ('before', 'before'), ('fl.', 'fl.')], max_length=10),
        ),
        migrations.AlterField(
            model_name='composer',
            name='death_year_qualifier',
            field=models.CharField(blank=True, choices=[('', '—'), ('c.', 'c.'), ('after', 'after'), ('before', 'before'), ('fl.', 'fl.')], max_length=10),
        ),
    ]
