# Generated by Django 6.0.1 on 2026-06-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0005_composer_dates_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='written_for_polyphonica',
            field=models.BooleanField(default=False, help_text='Commissioned or written specifically for Polyphonica'),
        ),
    ]
