# Generated by Django 6.0.1 on 2026-01-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio')], max_length=10)),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo URL')),
                ('video_embed_code', models.TextField(blank=True, help_text='Custom embed code (optional)')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('audio_url', models.URLField(blank=True, help_text='External audio URL (SoundCloud, etc.)')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='media_thumbnails/')),
                ('category', models.CharField(blank=True, help_text="e.g., 'Live Performance', 'Studio Recording'", max_length=100)),
                ('performance_date', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Media Item',
                'verbose_name_plural': 'Media Items',
                'ordering': ['-is_featured', 'display_order', '-date_added'],
            },
        ),
    ]
