# Generated by Django 6.0.1 on 2026-01-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='caption',
            field=models.CharField(blank=True, help_text='Photo caption or credit', max_length=500),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='press_photos/'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='media_type',
            field=models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('image', 'Image')], max_length=10),
        ),
    ]
