# Generated by Django 6.0.1 on 2026-01-26 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('concerts', '0005_add_performance_indexes'),
        ('workshops', '0003_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('venue_hire', 'Venue Hire'), ('refreshments', 'Refreshments'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('expense_date', models.DateField(db_index=True)),
                ('receipt', models.FileField(blank=True, help_text='Upload receipt image or PDF', null=True, upload_to='expense_receipts/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='concerts.concert')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_created', to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='workshops.workshop')),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['category', 'expense_date'], name='finance_exp_categor_095875_idx')],
            },
        ),
        migrations.CreateModel(
            name='StripeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('workshop', 'Workshop Registration'), ('concert', 'Concert Ticket')], max_length=20)),
                ('payment_intent_id', models.CharField(db_index=True, max_length=255)),
                ('charge_id', models.CharField(blank=True, max_length=255)),
                ('balance_transaction_id', models.CharField(blank=True, max_length=255)),
                ('gross_amount', models.PositiveIntegerField(help_text='Amount in pence')),
                ('stripe_fee', models.PositiveIntegerField(help_text='Stripe fee in pence')),
                ('net_amount', models.PositiveIntegerField(help_text='Net amount in pence')),
                ('transaction_date', models.DateTimeField(db_index=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concert_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stripe_transaction', to='concerts.concertticketorder')),
                ('workshop_registration', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stripe_transaction', to='workshops.workshopregistration')),
            ],
            options={
                'ordering': ['-transaction_date'],
                'indexes': [models.Index(fields=['transaction_type', 'transaction_date'], name='finance_str_transac_b89c8f_idx')],
            },
        ),
    ]
