# Generated by Django 6.0.1 on 2026-01-21 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, help_text='Brief summary for listings', max_length=300)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_hours', models.DecimalField(decimal_places=1, default=2, max_digits=4)),
                ('delivery_method', models.CharField(choices=[('online', 'Online'), ('in_person', 'In-Person'), ('hybrid', 'Hybrid')], default='in_person', max_length=20)),
                ('venue_name', models.CharField(blank=True, max_length=200)),
                ('venue_address', models.TextField(blank=True)),
                ('venue_postcode', models.CharField(blank=True, max_length=20)),
                ('venue_map_link', models.URLField(blank=True)),
                ('meeting_link', models.URLField(blank=True, help_text='Zoom/Meet link (only shown to registered participants)')),
                ('meeting_password', models.CharField(blank=True, max_length=50)),
                ('prerequisites', models.TextField(blank=True, help_text='Required knowledge or skills')),
                ('materials_needed', models.TextField(blank=True, help_text='What to bring')),
                ('image', models.ImageField(blank=True, null=True, upload_to='workshops/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_participants', models.PositiveIntegerField(default=20)),
                ('current_registrations', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(unique=True)),
                ('content', models.TextField(help_text='Terms and conditions text (supports Markdown)')),
                ('effective_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Workshop Terms',
                'verbose_name_plural': 'Workshop Terms',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='workshop_materials/')),
                ('available_before', models.BooleanField(default=True, help_text='Available before the workshop')),
                ('available_after', models.BooleanField(default=True, help_text='Available after the workshop')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='workshops.workshop')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('attended', 'Attended'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('special_requirements', models.TextField(blank=True, help_text='Dietary, accessibility, etc.')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_registrations', to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='workshops.workshop')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('workshop', 'user')},
            },
        ),
    ]
