# Generated by Django 6.0.1 on 2026-01-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopregistration',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text='Emergency contact name and phone number', max_length=200),
        ),
        migrations.AddField(
            model_name='workshopregistration',
            name='instruments',
            field=models.TextField(blank=True, help_text='What instruments will you be bringing?'),
        ),
        migrations.AddField(
            model_name='workshopregistration',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
