# Generated by Django 6.0.1 on 2026-01-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_workshopregistration_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='workshopregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('attended', 'Attended'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='workshop',
            index=models.Index(fields=['status', 'date'], name='workshop_status_date_idx'),
        ),
    ]
