# Generated by Django 6.0.1 on 2026-01-31 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='hide_availability',
            field=models.BooleanField(default=False, help_text='Hide the availability section on the public page'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='legacy_bookings',
            field=models.PositiveIntegerField(default=0, help_text='Bookings from legacy system (e.g. Stripe) not yet imported'),
        ),
    ]
