# Generated by Django 6.0.1 on 2026-01-21 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField()),
                ('programme', models.TextField(blank=True, help_text='Concert programme/repertoire')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('doors_open', models.TimeField(blank=True, help_text='When doors open (optional)', null=True)),
                ('venue_name', models.CharField(max_length=200)),
                ('venue_address', models.TextField(blank=True)),
                ('venue_postcode', models.CharField(blank=True, max_length=20)),
                ('venue_map_link', models.URLField(blank=True, help_text='Google Maps or similar link')),
                ('image', models.ImageField(blank=True, null=True, upload_to='concerts/')),
                ('ticket_source', models.CharField(choices=[('internal', 'Sell on this site'), ('external', 'External ticket link'), ('none', 'No tickets (free entry or private)')], default='external', max_length=20)),
                ('external_ticket_url', models.URLField(blank=True, help_text='Link to external ticket seller')),
                ('full_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('discount_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('discount_label', models.CharField(default='Concessions (seniors, students, disabled)', help_text='Description of who qualifies for discount', max_length=100)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited', null=True)),
                ('tickets_sold', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='ConcertTicketOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('ticket_type', models.CharField(choices=[('full', 'Full Price'), ('discount', 'Discount')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='concerts.concert')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
