# Generated by Django 6.0.1 on 2026-01-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='ticket_source',
            field=models.CharField(choices=[('internal', 'Sell on this site'), ('external', 'External ticket link'), ('door', 'Available on the door'), ('none', 'No tickets (free entry or private)')], default='external', max_length=20),
        ),
    ]
