# Generated by Django 6.0.1 on 2026-01-23 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0002_add_door_ticket_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='programme',
        ),
    ]
