# Generated by Django 6.0.1 on 2026-01-23 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0003_remove_programme_field'),
        ('repertoire', '0003_movement'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='programme',
            field=models.ForeignKey(blank=True, help_text='Link to the repertoire programme for this concert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concerts', to='repertoire.programme'),
        ),
    ]
