# Generated by Django 6.0.1 on 2026-01-31 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0005_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='ticket_source',
            field=models.CharField(choices=[('internal', 'Sell on this site'), ('external', 'External ticket link'), ('door', 'Available on the door'), ('collection', 'Free entry with retiring collection'), ('free', 'Free entry')], default='external', max_length=20),
        ),
    ]
