# Generated by Django 6.0.1 on 2026-01-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerBio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, help_text="e.g., 'Soprano & Alto Recorders'", max_length=100)),
                ('bio', models.TextField(help_text='Player biography')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players/')),
                ('website', models.URLField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which to display')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Player Biography',
                'verbose_name_plural': 'Player Biographies',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TrioInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Polyphonica Recorder Trio', max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(help_text='Main description of the trio')),
                ('history', models.TextField(blank=True, help_text='History and background')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trio Information',
                'verbose_name_plural': 'Trio Information',
            },
        ),
    ]
