# Generated by Django 6.0.1 on 2026-01-22 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trioinfo',
            name='history',
        ),
    ]
