# Generated by Django 6.0.1 on 2026-01-22 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_remove_history_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerbio',
            name='role',
        ),
    ]
